discussion/discussion/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls)

]

discussion/todolist/urls.py
from django.urls import path
from . import views


app_name = 'todolist'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:todoitem_id>/', views.todoitem, name='todoitem'),
    path('eventitem/<int:eventitem_id>/', views.eventitem, name='eventitem'),
    path('update_profile/<int:user_id>', views.update_profile, name='update_profile'),

    
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
    path('change_password', views.change_password, name='change_password'),

    
    path('create_task', views.create_task, name="create_task"),
    path('<int:todoitem_id>/edit', views.update_task, name='update_task'),
    path('<int:todoitem_id>/delete', views.delete_task, name='delete_task'),
    
    
    path('create_event', views.create_event, name="create_event"),
]

discussion/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %} To Do App {% endblock %}</title>

	<!-- Bootstrap -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
	<!-- The "include" keyword unlike the "extends" keyword allows to inject specific templates in certain sections of the page -->
	{% include "navbar.html" %}
	{% block content %}
	{% endblock %}

	<!-- Bootstrap -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

discussion/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">To Do App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="./">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="create_task">Add Task</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="create_event">Add Event</a>
          </li>
  
          {% if request.user.id %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'todolist:update_profile' request.user.id %}">Update Profile</a>
            </li>
          {% endif %}
  
          {% if not request.user.id %}
            <li class="nav-item">
              <a class="nav-link" href="register">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="login">Login</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="logout">Logout</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  